# Generated by Django 3.2.3 on 2021-08-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_tag_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cart',
            field=models.BooleanField(default=False),
        ),
    ]
