# Generated by Django 3.2.3 on 2021-07-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0003_alter_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('top', 'top'), ('bottom', 'bottom'), ('dress', 'dress'), ('shoe', 'shoe'), ('outerwear', 'outerwear'), ('handbag', 'handbag'), ('other', 'other')], default='shoe', max_length=100),
        ),
    ]
