# Generated by Django 3.2.3 on 2021-08-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0004_auto_20210805_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='available',
        ),
    ]
