# Generated by Django 3.2.3 on 2021-07-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0006_alter_outfit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
