# Generated by Django 3.2.3 on 2021-07-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0007_alter_outfit_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfit',
            old_name='item',
            new_name='items',
        ),
    ]
