# Generated by Django 3.2.3 on 2021-08-04 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='short_intro',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_instagram',
        ),
    ]
